name: yesod-sql-session
version: 0.0.0.0
maintainer: Freckle Education
category: Web
github: freckle/yesod-sql-session
synopsis: SQL session backend for Yesod
description: |
  Use Persistent to store Yesod sessions

extra-doc-files:
  - README.md
  - CHANGELOG.md

extra-source-files:
  - package.yaml

language: GHC2021

ghc-options:
  - -Weverything
  - -Wno-all-missed-specialisations
  - -Wno-missed-specialisations
  - -Wno-missing-exported-signatures # re-enables missing-signatures
  - -Wno-missing-import-lists
  - -Wno-missing-kind-signatures
  - -Wno-missing-local-signatures
  - -Wno-missing-safe-haskell-mode
  - -Wno-monomorphism-restriction
  - -Wno-partial-fields
  - -Wno-prepositive-qualified-module
  - -Wno-safe
  - -Wno-unsafe
  - -fwrite-ide-info

dependencies:
  - base < 5

default-extensions:
  - AllowAmbiguousTypes
  - DeriveAnyClass
  - DerivingStrategies
  - DuplicateRecordFields
  - FunctionalDependencies
  - GADTs
  - ImpredicativeTypes
  - LambdaCase
  - NoFieldSelectors
  - NoImplicitPrelude
  - OverloadedRecordDot
  - OverloadedStrings
  - QuantifiedConstraints
  - RecordWildCards
  - TypeFamilies
  - UndecidableInstances

library:
  source-dirs: library
  dependencies:
    - internal

internal-libraries:
  internal:
    source-dirs: internal
    dependencies:
      - annotated-exception
      - base64
      - bytestring
      - containers
      - cookie
      - crypton
      - exceptions
      - http-types
      - mtl
      - persistent
      - stm
      - text
      - time
      - transformers
      - wai
      - yesod-core

tests:
  spec:
    main: Spec.hs
    source-dirs: tests
    ghc-options: -threaded -rtsopts "-with-rtsopts=-N"
    dependencies:
      - aeson
      - containers
      - cookie
      - hedgehog
      - hspec-hedgehog
      - hspec
      - internal
      - QuickCheck
      - random
      - text
      - time
      - wai
      - wai-extra
      - yesod
      - yesod-sql-session
      - yesod-test
