type-class-roots = true
roots = [
  "^Main.main$",
  "^Paths_",
  "^Yesod.Session.Persist.Yesod.makeSessionBackend$",
  "^Yesod.Session.Memcache.Yesod.makeSessionBackend$",
  "^Yesod.Session.Options.hoistOptions$",
]
